spring:
  application:
    name: sistema-de-moeda-estudantil

  config:
    import: optional:file:.env[.properties]
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH}
          starttls:
            enable: ${MAIL_STARTTLS}
          ssl:
            enable: ${MAIL_SSL}
        debug: ${MAIL_DEBUG}

  task:
    execution:
      pool:
        core-size: 2
        max-size: 4
        queue-capacity: 50
      thread-name-prefix: async-email-
    scheduling:
      pool:
        size: 2

server:
  port: 8080

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub